services:
  api:
    build: ./api
    container_name: api
    networks:
      - docker-web
  back:
    build: ./back
    container_name: back
    networks:
      - docker-web
  front:
    build: ./front
    container_name: front
    networks:
      - docker-web
    volumes:
      - static-pages:/volume/
    depends_on:
      - nginx
  web:
    build: ./web
    container_name: web
    networks:
      - docker-web
    volumes:
      - static-pages:/volume/
    depends_on:
      - nginx
  nginx:
    build: ./nginx
    container_name: nginx
    networks:
      - docker-web
    ports:
      - "80:80"
    volumes:
      - static-pages:/usr/share/nginx/html/
networks:
  docker-web:
    driver: bridge
volumes:
  static-pages:
    